global:
  scrape_interval: 15s
  scrape_timeout: 1s
  evaluation_interval: 15s
scrape_configs:
- job_name: server
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['server:8080']
    labels:
      service: 'app-service'